server:
  servlet:
    context-path: /api-car
spring:
  profiles:
    active:
  datasource:
    url: jdbc:postgresql://${HOST}:${PORT:5432}/${DB_NAME}?currentSchema=${SCHEMA}
    driver-class-name: org.postgresql.Driver
    username:  ${DB_USER}
    password: ${DB_PASSWORD}

    hikari:
      minimum-idle: 2
      idle-timeout: 40000
      maximum-pool-size: 10
      connection-timeout: 10000
      keepalive-time: 30000
      schema: ${SCHEMA}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true

  sql:
    init:
      schema-locations: ${SCHEMA}
  threads:
    virtual:
      enabled: true

